import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
const { SITE_NAME } = process.env

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: SITE_NAME,
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.className} dark`}>{children}</body>
    </html>
  )
}
